version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  subscriber-call-app-ui:
    platform: linux/x86_64
    container_name: subscriber-call-app-ui
    image: subscriber-call-app-ui
    build:
      context: subcriber-call-app/subcriber-call-app-ui/ui
      dockerfile: Dockerfile-ui
      target: production
    ports:
      - "3000:3000"
    networks:
      search_app_net:
        ipv4_address: 192.168.2.5
  subscriber-call-app-service:
    platform: linux/x86_64
    depends_on:
      rabbitmq:
        condition: service_started
    healthcheck:
      test: curl http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    container_name: subscriber-call-app-service
    image: subscriber-call-app-service
    build:
      dockerfile: subcriber-call-app/subscriber-call-app-service/Dockerfile-service
    ports:
      - "8080:8080"
    environment:
      - RABBIT_HOST=localhost
      - RABBIT_PASSWORD=guest
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=guest
  postgres:
    container_name: postgres
    image: postgres-test
    build:
      dockerfile: ./subcriber-call-manager-service/service/Dockerfile-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  subcriber-call-manager-service:
    platform: linux/x86_64
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    container_name: subcriber-call-manager-service
    image: subcriber-call-manager-service
    build:
      dockerfile: ./subcriber-call-manager-service/service/Dockerfile-service
    environment:
      POSTGRESQL_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/postgres
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      RABBIT_HOST: localhost
      RABBIT_PASSWORD: guest
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest