FROM maven:3.8.3-openjdk-17 as builder

WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src

ENV POSTGRESQL_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
ENV POSTGRESQL_USER=postgres
ENV POSTGRESQL_PASSWORD=postgres

ENV RABBIT_HOST=host.docker.internal
ENV RABBIT_PASSWORD=guest
ENV RABBIT_PORT=5672
ENV RABBIT_USERNAME=guest

RUN mvn  clean package -P development -DskipTests

FROM openjdk:17-alpine
COPY --from=builder /app/target/service-1.0.0.jar /service.jar


EXPOSE 8083
CMD ["java", "-jar", "-Dspring.profiles.active=development", "service.jar"]