# this dockerfile is used by docker compose to run app locally
# this dockerfile is used by docker compose to run bdd tests

FROM node:18-alpine as builder
WORKDIR /app/src
COPY ./package*.json ./
COPY . /app/src
RUN npm install
RUN npm run build


FROM nginx:1.21.0-alpine as production
COPY --from=builder /app/src/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]