# this dockerfile is used by docker compose to run app locally
# this dockerfile is used by docker compose to run bdd tests

FROM node:16-alpine AS builder
WORKDIR /app/src
COPY ./package*.json ./
ARG GAMESYS_ARTIFACTORY_AUTH_TOKEN
COPY ./.npmrc.docker.local ./.npmrc
RUN npm ci && npm cache clean --force
COPY . /app/src
RUN npm run build

FROM nginx:1.21.0-alpine as production
COPY --from=builder /app/src/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8083
CMD ["nginx", "-g", "daemon off;"]