# this dockerfile is used by docker compose to run app locally
# this dockerfile is used by docker compose to run bdd tests

FROM node:18-alpine
WORKDIR /app/src
COPY ./package*.json ./
COPY . /app/src
EXPOSE 3000
RUN npm install
CMD ["npm", "start"]