spring:
  webservices:
    path: /subscriber-call-app/service/
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: ${RABBIT_PASSWORD:guest}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}

rabbitmq-settings:
  queues:
    start-call: start_call
    finish-call: finish_call
  exchange: rabbit_exchange
  routing-keys:
    start-call: start_call_routingkey
    finish-call: finish_call_routingkey




server:
  port: 8080
  jetty:
    threads:
      idle-timeout: 1000
      max: 20
      min: 10

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: healthcheck

subscriber-call-manager-service:
  host: ${SUBSCRIBER_CALL_MANAGER_HOST:http://localhost:8083}
  path: /subscriber-call-manager/service