FROM maven:3.8.3-openjdk-17 as builder
WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src

ENV RABBIT_HOST=host.docker.internal
ENV RABBIT_PASSWORD=guest
ENV RABBIT_PORT=5672
ENV RABBIT_USERNAME=guest
ENV SUBSCRIBER_CALL_MANAGER_HOST=http://host.docker.internal:8083

RUN mvn clean package -DskipTests

FROM openjdk:17-alpine
COPY --from=builder /app/target/bff-1.0.0.jar /bff.jar


EXPOSE 8080
CMD ["java", "-jar", "-Dspring.profiles.active=development", "bff.jar"]