FROM eclipse-temurin:17-jdk-jammy as base
WORKDIR /app

COPY ../.mvn .mvn
COPY ../mvnw pom.xml ./
RUN ./mvnw dependency:resolve

COPY src ./src

ENV POSTGRESQL_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
ENV POSTGRESQL_USER=postgres
ENV POSTGRESQL_PASSWORD=postgres

CMD ["./mvnw", "spring-boot:run"]